create table if not exists settings (
  id bigint generated by default as identity primary key,
  assistant_name text,
  company_name text,
  notify_email text,
  system_prompt text,
  faq text,
  created_at timestamptz default now()
);

create table if not exists calls (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  call_sid text,
  event_type text,
  from_number text,
  to_number text,
  transcript text,
  summary text
);
